local M = {}

function M.config()
  require('aerial').setup({
    attach_mode = "global",
    backends = { "lsp", "treesitter", "markdown" },
    min_width = 28,
    show_guides = true,
    filter_kind = {
      "Array",
      "Boolean",
      "Class",
      "Constant",
      "Constructor",
      "Enum",
      "EnumMember",
      "Event",
      "Field",
      "File",
      "Function",
      "Interface",
      "Key",
      "Method",
      "Module",
      "Namespace",
      "Null",
      "Number",
      "Object",
      "Operator",
      "Package",
      "Property",
      "String",
      "Struct",
      "TypeParameter",
      "Variable",
    },
    icons = {
      Array = "",
      Boolean = "⊨",
      Class = "",
      Constant = "",
      Constructor = "",
      Key = "",
      Function = "ƒ",
      Method = "ƒ",
      Namespace = "",
      Null = "NULL",
      Number = "#",
      Object = "⦿",
      Property = "",
      TypeParameter = "𝙏",
      Variable = "",
      Enum = "ℰ",
      Package = "",
      EnumMember = "",
      File = "",
      Module = "",
      Field = "",
      Interface = "ﰮ",
      String = "𝓐",
      Struct = "𝓢",
      Event = "",
      Operator = "+",
    },
    guides = {
      mid_item = "├ ",
      last_item = "└ ",
      nested_top = "│ ",
      whitespace = "  ",
    },
  })
end

return M
